# ========== CONFIGURATION GÉNÉRALE ==========
server.port=8080

# ========== CONFIGURATION UPLOAD DE FICHIERS ==========
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=2MB

# ========== CONFIGURATION H2 ==========
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# URL pour base H2 en mode fichier dans home utilisateur (~)
spring.datasource.url=jdbc:h2:file:~/stagesdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialecte Hibernate pour H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Mise à jour automatique du schéma (utile en dev)
spring.jpa.hibernate.ddl-auto=update

# Permet de ne pas générer un nom unique de datasource (utile pour la console H2)
spring.datasource.generate-unique-name=false
debug=true
